# Generated by Django 2.0.7 on 2020-09-06 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='MyCart',
        ),
    ]
